apiVersion: 1
datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    user: postgres
    secureJsonData:
      password: kro_local_2026
    jsonData:
      database: kro
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
    isDefault: true
    editable: false
